[Nina] Calculator-step1 구현 완료
JNU-econovation/javascript-study pull request #24
Opened 2019-03-05 13:03 UTC by inhasuh

사실 구현 완료는 아닙니다. 
`function check()`에 대한 리뷰가 필요합니다. 에러 체크를 도와주세요.

2019-03-05 14:00 UTC, GiPyoo reviewed
잘하셨습니다. 그런데 완성이 안된경우에는 올리는 것보다 슬랙의 질문 란을 이용해 주세요. 성실히 답해 드리겠습니다. 아래 리뷰 반영 부탁드립니다. 반영 후 코멘트 날려주세요. 감사합니다.

2019-03-05 14:00 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +    if((/[%*/+-]/.exec(inputValue.value))!=null && (left ==""|| right =="") || isNaN(left)){
조금 더 간단히 만들 수 있을 것 같습니다. 질문 글에 올려주시면 스레드로 기능에 대해 알려드리겠습니다.

2019-03-05 14:00 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +  var windowMath = /[%*/+-]/g;
객체를 반환하는 함수인데 save라는 이름은 어색한 것 같습니다. 무언가를 얻는 다는 개념으로 함수 의미를 짖는 것은 어떤가요?

2019-03-05 14:00 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +  var windowArea = /\d+/g;
window~~ 는 전역객체의 이름으로 혼선의 여지가 있고 정규표현식과 window가 어울리는 것 같지 않습니다. 수정이 필요해 보입니다.

2019-03-05 14:00 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +function calculator(){
함수이름은 동사로 해야 합니다.

2019-03-05 14:00 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +function Math(left, right, sign){
left나 right가 숫자임을 알 수 있게 이름을 지어주는 것이 어떨까요?

2019-03-05 14:57 UTC, corykim0829 requested changes
열심히 잘 구현하셨습니다! 조금 더 네이밍에 대해 생각해보시고 다른 사람 코드 참고하시면 좋을 것 같습니다. 리팩토링을 조금 더 하시고 push 해주세요~

2019-03-05 14:57 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +  var useful = {
객체 네이밍 컨밴션은 대문자를 사용합니다! step2 과제 공지의 네이밍 컨밴션을 참고하면 좋을 것 같습니다.

2019-03-05 14:57 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +  return resultValue;
여기서 resultValue를 왜 return하나요?

2019-03-06 14:38 UTC, forbid403 commented on public/calculator-step1/step1-cal.html
> +  <form action="" name="cal">
form 태그는 지워도 될것같아유

2019-03-27 02:34 UTC, corykim0829 requested changes
수고하셨습니다. func들간의 공백 추가해주시고 리뷰들 빠르게 반영 부탁드립니다~

2019-03-27 02:34 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +  return resultValue;
왜 return 하는지 아직 해결이 되지 않은 것 같습니다! 확인부탁드립니다~

2019-03-27 02:34 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +  var result = {
result 보다는 operator들을 가지고 있는 객체라는 의미가 전달되면 좋을 것 같아요

2019-03-27 02:34 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +  var blankMath = /[%*/+-]/g;
var let const를 공부해 보시고 바꿔보세요!

2019-03-27 02:34 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +    if((/[%*/+-]/.exec(inputValue.value))!=null || (leftnum ==""|| rightnum =="") || isNaN(leftnum)){
`(leftnum ==""|| rightnum =="")` 불필요한 괄호 같습니다.

2019-03-27 02:34 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +    if((/[%*/+-]/.exec(inputValue.value))!=null || (leftnum ==""|| rightnum =="") || isNaN(leftnum)){
isNan 함수가 없습니다!

2019-03-27 02:34 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +function check(inputValue, leftnum, rightnum){
이 함수의 리턴값이 사용되는 것 같은데 굳이 checkSign 변수를 선언하지 않아도 될 것 같습니다! 더 간결하게 수정해주세요

2019-03-27 02:34 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +    if(event.key.match(numRex)){
정규식으로 키 매칭한 부분이 좋네요!

2019-03-27 02:34 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +    if(element.keyCode == 8){
이전에 Kuma님이 말씀하신 하드 코딩 부분 해결되지 않았습니다!

2019-03-27 04:20 UTC, GiPyoo requested changes
수고하셨습니다. 아래 리뷰 반영 부탁드려요!! 👍 👍 👍

2019-03-27 04:20 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +      isClicked = false;
const 변수인데 false 로 재할당이 불가능할 것 같습니다. isClicked의 재선언을 방지하고 재할당을 허용하고 싶다면 채const 대신에 let을 사용하는 것은 어떨까요?

2019-03-27 04:20 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +  console.log("clear");
console 값을 지워 주시면 더 깨끗할 것 같습니다. 😄

2019-03-27 04:20 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +    if((/[%*/+-]/.exec(inputValue.value))!=null || (leftnum ==""|| rightnum =="") || isNaN(leftnum)){
@corykim0829 isNaN은 window에서 정의된 함수인 것 같습니다.

2019-03-27 04:20 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +  var result = {
객체의 네이밍은 대문자로 시작하는 것이 좋을 것 같습니다.

2019-03-27 04:20 UTC, GiPyoo commented on public/calculator-step1/step1-cal.js
> +
불필요한 빈 줄 같습니다.

2019-04-05 02:15 UTC, corykim0829 requested changes
리뷰 반영해주시고 빠르게 진행해주세요

2019-04-05 02:15 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +function handle() {
handle 의미가 불명확합니다.

2019-04-05 02:15 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +function insert(inputValue){
인자는 value로 하면 ㄷ좋을 것 같습니다.

2019-04-05 02:15 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +function check(inputValue, leftnum, rightnum){
이 함수가 사용되지 않는 것 같습니다.

2019-04-05 02:15 UTC, corykim0829 commented on public/calculator-step1/step1-cal.js
> +}
공백을 줘서 함수간 분리는 해주세요

2019-04-10 08:37 UTC, closed without merging