[Bird] "calculator-step1" 구현 완료
JNU-econovation/javascript-study pull request #25
Opened 2019-03-05 14:34 UTC by forbid403

엔터 누르면 계산 되는 기능과, backspace 누르면 지워지는 기능도 추가해 보았습니다 ^^*

2019-03-05 14:44 UTC, corykim0829 commented on public/calculator.js
> +    var input = document.getElementById("input");
계속 사용되는 부분은 함수로 만들면 좋을 것 같습니다.

2019-03-05 14:44 UTC, corykim0829 commented on public/calculator.js
> +    return ret;
ret 변수를 만들지 말고 바로 리턴하면 좋을 것 같습니다.

2019-03-05 14:44 UTC, corykim0829 commented on public/calculator.js
> +
불필요한 공백들을 제거하면 좋을 것 같습니다.

2019-03-05 14:44 UTC, corykim0829 commented on public/calculator.js
> +    }else return true;
else를 사용하면 안된다는 규칙이 있었습니다. 빼고 구현해주세요~

2019-03-05 14:51 UTC, corykim0829 requested changes
잘 구현하셨습니다. 조금만 더 리팩토링을 하시면 깔끔할 것 같아요! 변수명, 함수명, 인자명들을 조금 더 정확한 기능이 나타나도록 수정해주세요! 과제 공지에 있는 예외 처리들에 대해 검사를 추가하시고 다시 push해주세요~

2019-03-05 14:51 UTC, corykim0829 commented on public/calculator.js
> +function operator(e) {
함수명과 인자명이 직관적이지 못합니다. 함수명과 인자명을 보고 어떤 기능을 하는지 알 수 있도록 바꿔주세요

2019-03-05 14:51 UTC, corykim0829 commented on public/calculator.js
> +function minus(x, y){
인자명도 의미가 잘 전달되도록 바꿔주세요!

2019-03-06 04:31 UTC, forbid403 commented on public/calculator.js
> +function minus(x, y){
리뷰 반영했습니다~ 확인 부탁드려요

2019-03-06 12:42 UTC, GiPyoo reviewed
전체적으로 괜찮았습니다. 약간의 리팩토링이 필요해 보입니다. 아래 히뷰 반영해주시고 push 후 코멘트 남겨주세요.

2019-03-06 12:42 UTC, GiPyoo commented on public/calculator.html
> +            <td onclick= calc(this)>=</td>
되도록이면 함수이름을 본단어 그대로 적는 것이 좋습니다.

2019-03-06 12:42 UTC, GiPyoo commented on public/calculator.js
> +    });
e 의 경우 의미전달이 잘 안 될 수 있습니다. element가 어떤가요?

2019-03-06 12:42 UTC, GiPyoo commented on public/calculator.js
> +    }
else를 빼면 좋을 것 같습니다. 그리고 이코드에서 올가 났을 경우를 if문 하나 로처리하면 인덴트가 이렇게 깊어지지 않을 것입니다.

2019-03-06 14:32 UTC, forbid403 commented on public/calculator.js
> +    }
리뷰 반영 했습니다!!

2019-03-07 03:50 UTC, GiPyoo reviewed
굿굿 아래 리뷰 반영해주시고 push 코멩트 남겨주세요.

2019-03-07 03:50 UTC, GiPyoo commented on public/calculator.js
> +
함수로 나눠 주세요.

2019-03-07 03:55 UTC, corykim0829 requested changes
빠르게 피드백을 반영하여 수정하는 모습이 보기 매우 좋습니다. 코드도 잘 짜셨고 조금 더 함수의 기능에 맞게 네이밍과 공백 정리만 하시면 perfect할 것 같습니다. 반복되는 사용을 줄일려고 노력해보세요

2019-03-07 03:55 UTC, corykim0829 commented on public/calculator.js
> +        switch (operator[0]) {
**switch문을 쓰지 않고 구현해보세요!**

2019-03-07 03:55 UTC, corykim0829 commented on public/calculator.js
> +    return parseFloat(first) + parseFloat(second);
각 연산자 함수에 있는 parseFloat를 입력값을 넣을 때 바꾸면 반복되는 parse 사용을 줄일 수 있을 것 같습니다.

2019-03-07 03:55 UTC, corykim0829 commented on public/calculator.js
> +function bringInput() {
bring 보다는 get이 좋을 것 같습니다.

2019-03-07 03:55 UTC, corykim0829 commented on public/calculator.js
> +function operator(element) {
인자명이 element는 html의 요소를 뜻하는 것 같아 정확한 의미를 전달할 수 있는 인자명으로 수정하는게 좋을 것 같습니다.

2019-03-08 15:07 UTC, corykim0829 reviewed
공백 정리와 예외처리만 추가적으로 진행하시면 될 것 같아요! 좋은 코드였습니다.

2019-03-08 15:07 UTC, corykim0829 commented on public/calculator.js
>  function plus(first ,second){
아래 4개 함수들을 사용하는 곳이 없는 것 같아요! 연산 함수들은 객체 안에 구현하셨으니 삭제해도 될 것 같아요~

2019-03-08 15:07 UTC, corykim0829 commented on public/calculator.js
> +function check(splited) {
예외 처리가 과제에 명시된 것들을 모두 포함하지 못한 것 같아요. 이 예외 처리는 연산자 2개 이상, 숫자가 3개 이상 들어왔을 때만 처리가 될 것 같네요.
과제를 한번 더 읽어보고 나머지 예외처리를 생각해보시면 좋을 것 같아요!

2019-03-08 16:12 UTC, corykim0829 approved these changes
수고하셨어요~ 리뷰도 항상 빠르게 반영하시고 피드백 반영을 항상 바로바로 하셔서 보기 좋습니다! 머지해드릴게요~ 리뷰해드린 부분은 더 생각해보고 step2 진행할 때 수정해보세요!
머지된 JNU 저장소에 새롭게 remote 등록하고 fetch-rebase 하시고 step2 브랜치 새롭게 만들어서 진행하시면 됩니다. (공지사항 깃 문서 및 README.md 참고, 모르겠으면 질문!)

2019-03-08 16:12 UTC, corykim0829 commented on public/calculator.js
> +    if(check(result) && isFinite(result)){
좋은 함수 사용이에요~

2019-03-08 16:12 UTC, corykim0829 commented on public/calculator.js
> +function check(splited) {
다시 보니까 이 함수는 check() 라고하여 검사만 하는 리턴값이 없는 함수 같아 보입니다. 이 부분에 더 생각해보시면 좋을 것 같아요~

2019-03-08 16:12 UTC, merged