Calculator-step1 구현 완료
JNU-econovation/javascript-study pull request #26
Opened 2019-03-07 12:25 UTC by Parkhyunseo

깜빡하고 커밋을 나눠서 못했습니다...
다음 부터 꼭 나눌게요!

2019-03-07 12:37 UTC, forbid403 commented on public/calculate-step1/index.html
> +                        <div class="clickable" id="*" onClick='clickAsterisk()'>*</div>
입력받는 함수를 하나로 통합해보세용

2019-03-07 12:39 UTC, forbid403 commented on public/calculate-step1/static/js/calculator.js
> +                break;
바로 return을 해버리면 break를 안써도 될것같습니다

2019-03-07 12:54 UTC, corykim0829 requested changes
구현을 정말 잘하셨네요! 네이밍도 잘하셨고 여러 문법도 사용하셔서 배울게 많습니다. input 부분 코드를 더 줄이시면 좋을 것 같습니다. input부분을 중심적으로 코드를 간소화 해보세요~
그리고 PR 보낼 때 규칙을 지켜서 항상 [Kuma]를 앞에 붙여주세요~
[Kuma] Calculator-step1 구현 완료

2019-03-07 12:54 UTC, corykim0829 commented on public/calculate-step1/static/js/input.js
> +}
모든 input 함수를 통합해도 될 것 같습니다. input 부분 코드를 최대한 줄여보도록 해보세요!

2019-03-07 13:18 UTC, mywnajsldkf commented
리뷰보고 배우고 갑니다!👍

2019-03-10 05:39 UTC, GiPyoo requested changes
잘하셧습니다. 하지만 필요없는 부분이 조금 있는 것 같습니다. 리뷰 반영 부탁드립니다.

2019-03-10 05:39 UTC, GiPyoo commented on public/calculate-step1/index.html
> +        <script type="text/javascript" src="./static/js/utils.js"></script>
파일 분리는 많이 좋아보입니다. 자바스크리브 파일을 분리할 때 소규모 작업시에는 (어떤작업.기능.js) 로 이름을 짓는 것이 좋을 것 같습니다. (수정 사항 아닙니다. 잘하셧습니다.)

2019-03-10 05:39 UTC, GiPyoo commented on public/calculate-step1/static/js/input.js
> +    });
이러한 하드 코딩을 조금더 소프트하게 짤 수 있을 것 같습니다. html을 이용하면 좋을 것 같습니다.

2019-03-10 05:39 UTC, GiPyoo commented on public/calculate-step1/index.html
> +                    </div>
위 html 태그들에서 id를 사용하지 않는 것 같습니다. 사용하지 않는다면 쓰지 않는 것이 맞는 것 같습니다.

2019-03-10 05:39 UTC, GiPyoo commented on public/calculate-step1/static/js/calculator.js
> +}
객체의 형식은 정말 좋습니다. 하지만 조금 돌아 가는 것 같습니다. 많이 줄일 수 있을 겁니다.

2019-03-10 05:39 UTC, GiPyoo commented on public/calculate-step1/static/js/input.js
> +    popExpressionView();
과대 포장 인 것 같아요. 인자도 없고 반환 값도 없는 것 같아서용

2019-03-10 05:39 UTC, GiPyoo commented on public/calculate-step1/static/js/utils.js
> +
파라미터 이름이 명확하지 않는 것 같습니다.

2019-03-10 05:50 UTC, Parkhyunseo commented on public/calculate-step1/index.html
> +                    </div>
반영했습니다!

2019-03-10 05:53 UTC, Parkhyunseo commented on public/calculate-step1/static/js/input.js
> +    popExpressionView();
확장성을위해 event와 기능을 분리해서 작성했지만, 그렇게 보이기도 하네요. 수정하겠습니다!

2019-03-10 05:58 UTC, Parkhyunseo commented on public/calculate-step1/static/js/calculator.js
> +}
(기능 / mapper / 실행)으로 역할에 맞는 일만 하게끔 하기위해서 나누었습니다! 개선 사항을 조금 더 자세히 말씀해주실 수 있을까요?

2019-03-10 06:12 UTC, Parkhyunseo commented on public/calculate-step1/static/js/input.js
> +    });
html을 처음에 사용하려 했지만, 몇 가지 문제점이 있어 javascript의 bindKey함수에 묶어서 관리하게 되었습니다. 

1. eventListener 객체가 바뀔 수 있다.
2. 공통적으로 실행되어야할 코드가 있다.
3. 관리가 어렵다.

React에서의 Component 구조로는 재활용성이 높은 경우에 html으로 작성하는 편이 좋겠지만, 이 부분에서는 html코드를 재활용하지 않기 때문에 한 곳에서 관리하는 편이 더 깔끔하다고 판단했습니다!

2019-03-10 06:41 UTC, GiPyoo reviewed
전반적으로 잘 반영 된 것 같습니다. 아래 리뷰에 대한 것들을 올려 보았습니다.

2019-03-10 06:41 UTC, GiPyoo commented on public/calculate-step1/static/js/calculator.js
> +}
나누는 것도 좋지만, 음 동작이 복잡하지 않기 때문에 기능과 mapper를 합치고 run 안에 mapper를 가지고 있는 형태가 더 간단 할 거 같다고 생각됩니다. 코드 자체는 클린하지만 이러한 연산자가 수 십가지가 될경우 이러한 코드는 조금 많이 길어 질 것 같아서 말씀 드렸습니다. 👍 👍

2019-03-10 06:41 UTC, GiPyoo commented on public/calculate-step1/static/js/input.js
> +    });
그렇군요 👍  그렇다면 이러한 하드 코딩을 피하기 위해서 window 객체의 keyCode 가 아닌 key를 이용하는 것은 어떤가요?

2019-03-10 07:08 UTC, Parkhyunseo commented on public/calculate-step1/static/js/input.js
> +    });
key라는게 있었네요! 하나 배워갑니다. 감사합니다 ㅎㅎ

2019-03-10 07:09 UTC, Parkhyunseo commented
리뷰 반영했습니다!!

2019-03-10 12:21 UTC, hotheadfactory reviewed
전채적으로 깔끔하게 잘 하신 것 같습니다!

2019-03-10 12:21 UTC, hotheadfactory commented on public/calculate-step1/index.html
> +                        <div class="clickable" id="*" onClick='clickAsterisk()'>*</div>
사칙연산 입력 받는 함수는 하나로 통합해도 될 것 같습니다. 숫자 입력까지 통합하면 더 좋고요

2019-03-10 12:21 UTC, hotheadfactory commented on public/calculate-step1/static/js/calculator.js
> +        return a/b;
modulo 함수가 나머지를 구하는 것으로 보이는데, a/b라는 나눗셈 식이 들어가 있네요.

2019-03-11 02:03 UTC, closed without merging

2019-03-11 12:27 UTC, mywnajsldkf commented on public/calculate-step1/static/js/calculator.js
> +    plus : (a, b) => {
a와 b를 구체적으로 명시해주시면 좋겠습니다!