[bird] calculator-step 2 구현 완료
JNU-econovation/javascript-study pull request #27
Opened 2019-03-15 13:53 UTC by forbid403

도움 주셔서 완료 했습니다! ^0^

2019-03-17 10:08 UTC, GiPyoo requested changes
아래 리뷰 말고도 상태를 변화 시키는 경우가 있던데 이러한 상태 변화를 바꿔주는 함수를 따로 만들면 어떨까 싶습니다. 리뷰 반영 부탁드려요

2019-03-17 10:08 UTC, GiPyoo commented on public/calculator.js
> +
고정된 값들은 const로 큐와 타이핑이나 닷 유즈드는 let으로 하는 것이 어떻까요? let, const var의 차이점에 대해서 공부해주시고 담글로 달아주세요.

2019-03-17 10:08 UTC, GiPyoo commented on public/calculator.js
> +    console.log(result)
로그가 남아 있습니다 정리해주세용

2019-03-17 10:45 UTC, corykim0829 requested changes
수고하셨습니다. 피드백 반영하시고 연속된 계산도 할 수 있도록 해보세요!

2019-03-17 10:45 UTC, corykim0829 commented on public/calculator.js
> +function initInput() {
initInput은 input을 시작한다는 말 같아서 setup~ 이나 initializeForInput 이 나쁘지 않을 것 같아요

2019-03-17 10:45 UTC, corykim0829 commented on public/calculator.js
> +function clearClicked(element) {
clicked라고 과거형으로 선언해 버리면 인자가 필요없는 느낌이 들어요 clickNumber~ 처럼 인자가 목적어로 들어갔을 때 자연스럽게 고쳐보세요!

2019-03-17 10:45 UTC, corykim0829 commented on public/calculator.js
> +function operClicked(element) {
oper라고 줄여쓰면 혼돈을 줄 수 있기 때문에 줄여쓰지 마세요

2019-03-17 10:45 UTC, corykim0829 commented on public/calculator.js
>  }
사용하는 곳이 없는 함수 같아요 정리해주세요

2019-03-17 10:45 UTC, corykim0829 commented on public/calculator.js
> +    var second = queue.pop();
var라고 안써도 될 것 같아요 const, let 중에 고민해보세요

2019-03-17 10:45 UTC, corykim0829 commented on public/calculator.js
> +window.addEventListener('keydown', function(element){
하드 코딩 같다는 생각이 드네요 이 부분이 너무 복잡해 보이는데, day1 drum 과제를 참고하여 리팩토링 해보세요

2019-03-18 02:36 UTC, forbid403 commented on public/calculator.js
> +
[const]
scope : {} 단위
변수의 값 변경 불가

[let]
scope : {} 단위
변수의 값 변경 가능

[var]
scope : function 단위
변수의 값 변경 가능

var은 유연한 변수 선언 방법이지만 코드의 불확실성을 늘리게 된다. (재선언 가능하고 값이 블록 밖에서도 변경 되기 때문에)
let, var을 사용하는 것을 권장한다.

2019-03-18 02:45 UTC, hotheadfactory reviewed
큐로 구현한 점이 인상깊었습니다.

2019-03-18 02:45 UTC, hotheadfactory commented on public/calculator.js
> +var dotUsed = false;
굳이 dot을 눌렀음을 표시해 줄 필요가 있나요?

2019-03-18 02:52 UTC, forbid403 commented on public/calculator.js
> +var dotUsed = false;
2번 연속 눌러짐을 막기 위함입니다

2019-03-22 01:39 UTC, Parkhyunseo commented on public/calculator.js
>      return document.getElementById("input");
이렇게 되면, 함수를 매번 호출 할 때 마다 Element를 검색하기 때문에 따로 변수에 저장하는게 좋겠습니다.

2019-03-23 04:51 UTC, Parkhyunseo commented
잘하셨습니다! 머지해드릴게요~

2019-03-23 04:51 UTC, merged