[hiro] clock-step3 구현 완료
JNU-econovation/javascript-study pull request #29
Opened 2019-03-19 04:47 UTC by hotheadfactory

기존에 개인적으로 만들어 썼던 수능타이머를 기반으로 요구사항을 구현해 봤습니다. 부족한 점 있으면 피드백 부탁드려요!

2019-03-22 01:46 UTC, Parkhyunseo commented on clock/clock.js
>      var d = 0, d1 = 0, d2 = 0, d3 = 0, h = 0, h1 = 0, h2 = 0, m1 = 0, m2 = 0, s1 = 0, s2 = 0, ms1 = 0, ms2 = 0, ms3 = 0;
정리가 필요합니다.

2019-03-22 01:46 UTC, Parkhyunseo commented on clock/clock.js
> +    document.getElementById("time-mili3").innerHTML = ms3;
코드를 더 줄일 수 있을 것 같습니다.

2019-03-23 05:01 UTC, corykim0829 requested changes

2019-03-23 05:01 UTC, corykim0829 commented on clock/clock.js
> +    if(isClock == 1) {
하드코딩입니다~ 수정해주세요

2019-03-24 01:50 UTC, GiPyoo requested changes
전체적으로 조금 아쉽습니다. 아래 리뷰 반영 부탁드립니다.

2019-03-24 01:50 UTC, GiPyoo commented on clock/clock.html
> +    <span id="dday-timer" class="alert"></span>
id 네이밍에 하이픈을 쓰지 않습니다.

2019-03-24 01:50 UTC, GiPyoo commented on clock/clock.js
> +var isStopped = 0;
상태를 나타내는 변수입니다. var 보다는 let이 어울리는 것 같습니다. 변수명도 조금 아쉽습니다.

2019-03-24 01:50 UTC, GiPyoo commented on clock/clock.js
> +    var d = 0, d1 = 0, d2 = 0, d3 = 0, h = 0, h1 = 0, h2 = 0, m1 = 0, m2 = 0, s1 = 0, s2 = 0, ms1 = 0, ms2 = 0, ms3 = 0;
너무 하드 코딩인 것같습니다. 다른 방법을 생각해 보는게 좋을 것 같습니다.

2019-03-24 01:50 UTC, GiPyoo commented on clock/clock.js
> +    document.getElementById("time-mili3").innerHTML = ms3;
로직을 바꾸면 더 나아질 것 같습니다.

2019-03-24 07:59 UTC, hotheadfactory commented on clock/clock.js
> +    document.getElementById("time-mili3").innerHTML = ms3;
수정했습니당

2019-03-24 16:50 UTC, corykim0829 requested changes
수고하셨습니다. 리뷰 반영해주세요~

2019-03-24 16:50 UTC, corykim0829 commented on clock/clock.js
> +let isClock = 1;
isClock은 bool 타입으로 쓰는게 좋을 것 같습니다

2019-03-24 16:50 UTC, corykim0829 commented on clock/clock.js
> +let isStopped = 0;
마찬가지로 bool 타입이 좋을 것 같습니다.

2019-03-24 16:50 UTC, corykim0829 commented on clock/clock.js
> +function expandDigit(n, width) {
변수명들이 어떤 역할을 하는지 이해가 잘 안갑니다. n으로 쓰지 말고 의미를 담도록 인자명을 바꿔주세요! width도 변경하는게 좋을 것 같아요

2019-03-26 10:25 UTC, hotheadfactory commented on clock/clock.js
> +function expandDigit(n, width) {
반영했습니다!

2019-03-27 04:25 UTC, GiPyoo requested changes
수고하셨습니다. 전체적으로 줄일 수 있는 함수들이 많은 것 같습니다. 아래 리뷰 반영 부탁드려요 👍 👍 👍

2019-03-27 04:25 UTC, GiPyoo commented on clock/clock.css
> +
불필요한 빈 줄 같습니다.

2019-03-27 04:25 UTC, GiPyoo commented on clock/clock.html
> +</script>
불필요한 태그들인 것 같습니다.

2019-03-27 04:25 UTC, GiPyoo commented on clock/clock.js
> +    var h = 0, m = 0, s = 0, ms = 0;
변수의 의미가 불분명한 것 같습니다.

2019-03-27 04:25 UTC, GiPyoo commented on clock/clock.js
> +}
위 함수의 기능이 클락이 맞는지 아닌지만 구분한다는 기능 외에 추가적인 기능들이 있는 것 같습니다. 이런 부분들은 과감히 분리해 주시느게 좋을 것 같습니다.

2019-03-27 07:26 UTC, hotheadfactory commented on clock/clock.js
> +}
수정했습니다.

2019-03-27 07:52 UTC, corykim0829 requested changes

2019-03-27 07:52 UTC, corykim0829 commented on clock/clock.js
> +function stopWatch() {
함수명이 그냥 명사이면 컨벤션에 어긋납니다~

2019-03-30 13:28 UTC, GiPyoo requested changes
수고하셨습니다. 아래 리뷰 반영 부탁드립니다. 반영후 머지 해드리겠습니다. 👍 👍

2019-03-30 13:28 UTC, GiPyoo commented on clock/clock.js
> +  num = num + '';
문자열로 변환 하시는 것 같은데, 다른 사람이 보기에 알아보기 힘들 수도 있습니다. 하드코딩 인것 같습니다.

2019-03-30 13:28 UTC, GiPyoo commented on clock/clock.js
> +  }
위는 공백라인이 있는데 왜 이 조건절에는 없나요. 위를 수정하거나 이곳을 수정하여 통일성을 가지는 것이 좋아보입니다.

2019-03-30 13:36 UTC, hotheadfactory commented on clock/clock.js
> +  }
수정했습니다.

2019-03-30 14:10 UTC, merged