[Judy] Calculator step2 구현
JNU-econovation/javascript-study pull request #30
Opened 2019-03-20 05:37 UTC by mywnajsldkf

calculator step2 구현했습니다. 
step2 과제에서는 자료구조를 사용해도 된다고 하셨는데 아직 자료구조를 배우지 않아서 이해가 잘 안됩니다. 도움 주시면 감사하겠습니다 :)

2019-03-20 07:50 UTC, forbid403 commented on public/calculator-step2/calculatorSource.js
> +window.addEventListener('keydown', writeNum);
함수화 시켜주세요

2019-03-20 07:50 UTC, forbid403 commented on public/calculator-step2/calculatorSource.js
> +    var rightNum = parseFloat(numbers[1]);
const, var, let의 차이점을 검색 해 보시고 사용 해 보세용~

2019-03-20 07:50 UTC, forbid403 commented on public/calculator-step2/calculatorSource.js
> +function checkSplited(numbers){
사용되지 않는 함수같아요

2019-03-20 13:28 UTC, corykim0829 requested changes
구현 잘하셨습니다! 연속되는 계산도 가능하도록 만들어주세요

2019-03-20 13:28 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +function checkSymbol(symbol){
symbol이 겹치네요! 겹치지 않게 바꿔보세요!

2019-03-20 13:28 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +function startCal(input){
여기 인자가 현재 사용되고 있나요?

2019-03-20 13:28 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +function enter(char) {
enter보다는 입력한다는 의미로 바꾸면 좋겠습니다.

2019-03-20 13:28 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +    var input = document.getElementById('input');
이부분이 많이 사용되는데, 함수로 만들어서 사용하면 코드가 많이 줄 것 같아요!

2019-03-22 02:38 UTC, Parkhyunseo commented on public/calculator-step2/calculatorSource.js
> +    key.css('border','2px solid blue');
CSS에서 가능한 일이고 CSS에서 처리하는게 맞는 일인것 같습니다!
.key:hover {
  border : 2px solid blue
}
이렇게요

2019-03-26 09:31 UTC, mywnajsldkf commented on public/calculator-step2/calculatorSource.js
> +    key.css('border','2px solid blue');
오 잘 돌아가네요! 감사합니다

2019-03-26 12:11 UTC, corykim0829 requested changes
수고하셨습니다. 수정할 부분이 많다고 생각이 듭니다. 천천히 전체 흐름을 따라가보고 선언한 프로퍼티들을 사용하고 있는지 체크해보세요!
예외 처리도 추가해보시면 좋을 것 같습니다~

2019-03-26 12:11 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +function startCal(input){
이 곳 인자가 또 사용되지 않고 있습니다.

2019-03-26 12:11 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +var secondDot = false;
bool 변수는 is~로 시작하는게 맞는 표기법입니다.

2019-03-26 12:11 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +function checkSplited(numbers){
bool type 리턴 함수도 네이밍 컨벤션을 지키는게 좋을 것 같습니다.
https://soojin.ro/blog/naming-boolean-variables 참고!

2019-03-26 12:11 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +function calculate(symbol){
이 함수가 어디서 호출되고 있나요?

2019-03-26 12:11 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +    var input = getInput;
let, const, var 차이를 공부해보고 var보다 다른 타입으로 선언하는게 좋은지 생각해보세요~

2019-03-26 12:11 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +    var inputsymbol = /[+*/-]/g;
정규 표현식이라는 것을 알 수 있는 변수명으로 바꾸거나 굳이 변수로 만들지 않아도 괜찮을 것 같습니다.

2019-03-26 12:11 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +    return checkSymbol;
여기서 반환하는게 어디서 선언되어있는지 알 수 없습니다.

2019-03-26 12:11 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +    checkSplited(numbers);
이게 어떤 기능을 하는지 이해가 가지 않습니다.

2019-03-27 02:37 UTC, mywnajsldkf commented on public/calculator-step2/calculatorSource.js
> +    var input = getInput;
https://mywnajsldkf.tistory.com/3 
리뷰보고 공부해보았습니다!

2019-03-27 02:37 UTC, mywnajsldkf commented on public/calculator-step2/calculatorSource.js
> +function checkSplited(numbers){
고민했던건데 감사합니다!!

2019-03-27 02:55 UTC, mywnajsldkf commented on public/calculator-step2/calculatorSource.js
> +    var inputsymbol = /[+*/-]/g;
변수로 만들지 않는다는 말씀이 무엇일까요??ㅠㅠ 설명부탁드립니다

2019-03-28 06:18 UTC, forbid403 reviewed
잘 하셨습니다 :D 리뷰 반영 하시면 (다른분이) 머지 해드릴게요~

2019-03-28 06:18 UTC, forbid403 commented on public/calculator-step2/calculatorSource.js
> +function typeDot(char){
char의 의미가 무엇인가요?

2019-03-28 06:18 UTC, forbid403 commented on public/calculator-step2/calculatorSource.js
> +    let input = getInput;
type이 타이핑이 아니라 종류를 의미하는 것 같습니다

2019-03-28 08:22 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +    var inputsymbol = /[+*/-]/g;
바로 match 함수 인자 안에 넣어버려도 된다는 의미였어요!

2019-03-29 02:43 UTC, Parkhyunseo reviewed
반영 해주세요

2019-03-29 02:43 UTC, Parkhyunseo commented on public/calculator-step2/calculatorSource.js
> +function getInput(){
getInput이 리턴을 안합니다

2019-03-29 02:43 UTC, Parkhyunseo commented on public/calculator-step2/calculatorSource.js
> +    getInput.value = "";
getInput함수 실행을 하지 않습니다!

2019-03-29 02:45 UTC, corykim0829 requested changes

2019-03-29 02:45 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +function type(char) {
인자를 char라는 타입으로 하지 말고 명확한 의미를 갖는게 좋을 것 같아요~

2019-03-29 02:45 UTC, corykim0829 commented on public/calculator-step2/calculatorSource.js
> +function typeDot(char){
typeDot이 점 하나만 입력하기 때문에 인자를 없애도 될 것 같습니다!

2019-04-02 16:26 UTC, GiPyoo approved these changes
수고하셧습니다. 아래 리뷰 반영 해주시면 머지해드리겠습니다!! 👍 👍 쿠마님 리뷰 반영 부탁드려요 getInput에 리턴이 없다고 합니다. 그리고 중괄호 뒤에오는 세미 콜론 정리 부탁드려요.

2019-04-02 16:26 UTC, GiPyoo commented on public/calculator-step2/calculatorSource.js
> +};
세미콜론 정리해주세요.

2019-04-03 12:58 UTC, forbid403 reviewed
잘 봤습니다 😄 고생 많으셨어요.
키보드 자판이 아닌 html 화면을 누를 시에도 똑같이 작동 하는지의 여부가 알고 싶습니다.

2019-04-03 12:58 UTC, forbid403 commented on public/calculator-step2/calculatorSource.js
> +
라인 정리 해주세요

2019-04-03 12:58 UTC, forbid403 commented on public/calculator-step2/calculatorSource.js
> +    queue.push(Num);
첨자 부탁드려요~

2019-04-03 12:58 UTC, forbid403 commented on public/calculator-step2/calculatorSource.js
> +function typing(Num) {
인자명 camel case로 해주세여

2019-04-04 01:27 UTC, mywnajsldkf commented on public/calculator-step2/calculatorSource.js
> +    queue.push(Num);
코딩할때 첨자는 어떤 의미인가요?

2019-04-04 02:15 UTC, GiPyoo requested changes
수고하셨습니다. 아래 리뷰 반영 부탁드려요

2019-04-04 02:15 UTC, GiPyoo commented on public/calculator-step2/calculatorSource.js
> +    getInput.value = "";
혹시 이부분 작동하나요?

2019-04-04 02:15 UTC, GiPyoo commented on public/calculator-step2/calculatorSource.js
> +    key.typing(char);
char 이 선언된 적이 없습니다.

2019-04-04 02:15 UTC, GiPyoo commented on public/calculator-step2/calculatorSource.js
> +    } else
else 예약어를 쓰지 않습니다.

2019-04-29 16:42 UTC, GiPyoo approved these changes
수고 하셨습니다. 👍

2019-04-29 16:43 UTC, merged