[Kiki]step3 Clock 구현 완료
JNU-econovation/javascript-study pull request #33
Opened 2019-03-24 07:22 UTC by GiPyoo

리뷰 부탁드립니다.

2019-03-24 16:43 UTC, corykim0829 approved these changes
좋은 코드 잘 보았습니다. clock 부분 모듈러 계산 부분은 제가 생각했을 때에는 계산이 맞지 않는 것 같습니다! 한번 확인해주시고 stopwatch를 조금 더 간결하게 만들 수 있을 것 같습니다.
함수명 리팩토링도 전체적으로 한번 해주세요 수고하셨습니다.

2019-03-24 16:43 UTC, corykim0829 commented on public/clock/clock.js
> +function view() {
view 의미가 잘 전달이 안되는 것 같습니다!

2019-03-24 16:43 UTC, corykim0829 commented on public/clock/clock.js
> +    if (hours % 24 < 12) {
hours는 0~24시까지 있는데 24로 나눈 나머지는 똑같지 않나요?

2019-03-24 16:43 UTC, corykim0829 commented on public/clock/clock.js
> +    if (seconds % 60 < 10) {
여기도 마찬가지로 seconds %60은 값이 그대로 인 것 같습니다.

2019-03-24 16:43 UTC, corykim0829 commented on public/clock/clock.js
> +    const selectedMinute = minute % 60;
selectMinute을 왜 만들었는지 이해가 잘 안가네요.

2019-03-24 16:43 UTC, corykim0829 commented on public/clock/util.js
> +function removeTag() {
처음보는 코드에요 신기하네요

2019-03-24 16:43 UTC, corykim0829 commented on public/clock/util.js
> +function change() {
change, clear 함수에 목적어가 있으면 더 이해하는데 좋을 것 같아요

2019-03-27 02:43 UTC, Parkhyunseo reviewed
네이밍 규칙도 잘 지키셨고, 모듈을 나눠서 잘 구현하셨네요!  리뷰 반영 부탁드립니다~

2019-03-27 02:43 UTC, Parkhyunseo commented on public/clock/stopwatch.js
> +function doit() {
doit보다는 run이라는 이름이 더 좋을 것 같네요

2019-03-27 02:43 UTC, Parkhyunseo commented on public/clock/util.js
> +function addTag() {
string보다는 Document.createElement()를 사용하는게 좋을 것 같습니다!

2019-03-27 05:33 UTC, corykim0829 requested changes
수고하셨어요~ 조금만 더 리팩토링 해주세요~

2019-03-27 05:33 UTC, corykim0829 commented on public/clock/util.js
> +    if ($("#changingState").innerHTML == "stopwatch") {
이거 하드코딩... 아닐까요?

2019-03-27 05:33 UTC, corykim0829 commented on public/clock/util.js
> +function setEvent() {
setClickEvent가 더 좋아보이는데 어떻게 생각하시나요?

2019-03-27 05:33 UTC, corykim0829 commented on public/clock/stopwatch.js
> +    if (seconds < 10) {
삼항 연산자로 코드를 훨씬 줄일 수 있을 것 같습니다. 한번 써보시고 더 간결하다 싶은걸로 쓰세요~

2019-03-27 15:29 UTC, corykim0829 commented
kiki님 clock-step1이 무엇입니까... step3로 하기로 했는데..

2019-03-29 02:53 UTC, Parkhyunseo commented on public/clock/clock.js
> +    if ($("#changingState").innerHTML == "stopwatch") {
DOM element의 내용을 비교하지말고 객체나 변수로 상태를 기억해야해요

2019-03-29 02:54 UTC, Parkhyunseo commented on public/clock/clock.js
> +    if (hours < 12) {
삼항 연산자로 해결 하는게 깔끔할 것 같습니다!

2019-03-30 13:50 UTC, hotheadfactory reviewed
수고하셨습니다. 전반적으로 깔끔한 코드 같습니다 배우고 갑니다.

2019-03-30 13:50 UTC, hotheadfactory commented on public/clock/clock.js
> +        return;
자릿수 맞추기는 별도 함수로 빼는 것이 깔끔할 것 같습니다.

2019-03-30 14:55 UTC, corykim0829 requested changes

2019-03-30 14:55 UTC, corykim0829 commented on public/clock/clock.js
> +    hours < 12 ? meridiem = "AM" : meridiem = "PM"
선언과 동시에 삼항 연산자로 값 넣어줄 수 있습니다.

2019-03-30 14:55 UTC, corykim0829 commented on public/clock/structure.js
> +    stoping: "stop",
철자오류입니다. stopping으로 고쳐주세요

2019-03-30 14:55 UTC, corykim0829 commented on public/clock/structure.js
> +const UsableStatus = {
enableStatus가 더 적절한 것 같습니다.

2019-03-31 08:05 UTC, corykim0829 approved these changes

2019-03-31 08:05 UTC, merged