[sonia] step3-clock 구현 완료
JNU-econovation/javascript-study pull request #35
Opened 2019-03-25 05:04 UTC by forbid403

정각에 alert를 띄우게 해 놓았습니다!
감사합니다 ~~ 😀

2019-03-25 15:18 UTC, GiPyoo reviewed
수고하셧습니다. 👍 👍  아래 리뷰 반영부탁드립니다.

2019-03-25 15:18 UTC, GiPyoo commented on public/clock.js
> +var timeInput;
전역변수는 let으로 선언하는 것이 나을 것 같습니다.

2019-03-25 15:18 UTC, GiPyoo commented on public/clock.js
> +const halfOfDay = 12;
상수는 대문자 언더스코어를 사용하는 것이 좋을 것 같습니다.

2019-03-25 15:18 UTC, GiPyoo commented on public/stopwatch.js
> +var swTimeInput, startBtn, resetBtn;
swTimeInput이 어떤 의미인지 불분명한 것 같습니다.
전역변수는 var 보다 let이 나은 것 같습니다.

2019-03-25 15:18 UTC, GiPyoo commented on public/stopwatch.js
> +var timer;
위와 마찬가지로 let이 나은 것 같습니다.

2019-03-25 15:18 UTC, GiPyoo commented on public/stopwatch.js
> +        if (swMinute >= 60) {
이중 조건절은 지양해야합니다.

2019-03-25 15:29 UTC, corykim0829 requested changes

2019-03-25 15:29 UTC, corykim0829 commented on public/stopwatch.js
> +let btnClicked = false;
bool type이니 isBtnClicked가 더 좋은 표기법 같습니다.

2019-03-26 10:36 UTC, GiPyoo reviewed
👍 👍 아래 리뷰 반영 부탁드립니다.

2019-03-26 10:36 UTC, GiPyoo commented on public/stopwatch.js
> +function swTimeInit() {
함수의 이름이 불확실한 것 같습니다.

2019-03-26 10:36 UTC, GiPyoo commented on public/stopwatch.js
> +    stopWatchInput = document.getElementById("stopWatch");
변수의 이름이 동사와 같이 느껴져서 무언가를 하는 것으로 느낌이 듭니다.

2019-03-26 12:21 UTC, corykim0829 requested changes
수고하셨습니다. 조금 더 자연스럽게 수정할 곳이 있어보입니다. 화이팅!

2019-03-26 12:21 UTC, corykim0829 commented on public/clock.js
> +    timeSetting();
여기서 굳이 timeSetting()을 시작안해도 될 것 같습니다!

2019-03-26 12:21 UTC, corykim0829 commented on public/clock.js
> +    setClock(amOrPm, hour, minute, second);
setClockDisplay, setDisplay 같은게 더 어울릴 것 같아요

2019-03-26 12:21 UTC, corykim0829 commented on public/stopwatch.js
> +var stopWatchInput, startBtn, resetBtn;
let으로 해도 되지 않을까요?

2019-03-26 12:21 UTC, corykim0829 commented on public/stopwatch.js
> +function startBtnClicked() {
이 함수가 어떤 기능을 하는지 감이 잘 오지 않습니다. 이름 수정해주세요~

2019-03-26 12:21 UTC, corykim0829 commented on public/stopwatch.js
> +    timer = setInterval(add, 1000);
setInterval을 왜 timer에 넣나요?

2019-03-26 12:21 UTC, corykim0829 commented on public/stopwatch.js
> +function resetisBtnClicked() {
함수명 수정 부탁드립니다.

2019-03-27 03:09 UTC, hotheadfactory commented on public/stopwatch.js
> +     (swSecond > 9 ? swSecond : "0" + swSecond);
삼항연산자를 활용한 점은 좋으나 시분초 모두 하나의 함수로 처리 가능할 것 같습니다.

2019-03-27 09:15 UTC, forbid403 commented on public/stopwatch.js
> +    timer = setInterval(add, 1000);
clear interval 해주려고 넣었습니닷

2019-03-27 15:28 UTC, corykim0829 requested changes
수고하셨습니다. 함수들 네이밍 통일 해주시고 리뷰 반영 부탁드려요!

2019-03-27 15:28 UTC, corykim0829 commented on public/stopwatch.js
> +    swHour, swMinute, swSecond = 0;
질문까지 하셔놓고 왜 바꾸지 않으셨나요!! 바꿔주세요~

2019-03-27 15:28 UTC, corykim0829 commented on public/stopwatch.js
> +    swHour, swMinute, swSecond = 0;
이미 module을 나눴으니 그냥 hour, minute 이렇게 써도 상관없을 것 같습니다.

2019-03-27 15:28 UTC, corykim0829 commented on public/stopwatch.js
> +function stopWatchTimeInit() {
동사 + 목적어가 더 좋은 네이밍 같습니다.

2019-03-30 13:23 UTC, GiPyoo requested changes
수고하셨습니다. 라인 리팩토링 후 머지 해 드리겠습니다. 👍 👍

2019-03-30 13:23 UTC, GiPyoo commented on public/stopwatch.js
> +        stopTime(); return;
연달아 쓰지 않는 것이 좋을 것 같습니다.

2019-03-30 13:23 UTC, GiPyoo commented on public/stopwatch.js
> +     determineTime(hour) + ":" + determineTime(minute) + ":" + determineTime(second);
한줄에 넣는게 좋을 것 같습니다.

2019-03-30 14:43 UTC, merged