[sonia] step4 구현 완료
JNU-econovation/javascript-study pull request #37
Opened 2019-03-30 13:25 UTC by forbid403

http가 아닌 net으로 구현하였습니다~ 다른 분들 것도 보고싶네요 😆

2019-03-30 15:17 UTC, Parkhyunseo commented on day4/fileReading.js
> +    for(i in parsed.info) {
i앞에 let을 붙여 주는게 좋아요.

2019-03-30 15:17 UTC, Parkhyunseo commented on day4/client.js
> +var client = net.connect({port: 3000, host:'192.168.0.2'},function(){
port와 host 값을 변수화 해주세요!

2019-03-30 15:17 UTC, Parkhyunseo commented on day4/fileReading.js
> +    const array = fs.readFileSync('info.json');
Database나 File접근, 통신은 Async를 사용하는 편이 좋습니다
http://www.nextree.co.kr/p7292/

2019-04-03 06:49 UTC, GiPyoo requested changes
아래 리뷰 반영 부탁드립니다. 👍

2019-04-03 06:49 UTC, GiPyoo commented on day4/client.js
> +client.on('data',function(data){//data 이벤트 발생시 callback
client 가 data를 입력하면 바로 이 함수가 호출 되나요?

2019-04-03 06:49 UTC, GiPyoo commented on day4/fileReading.js
> +server.listen(port, host, 50000, function() {
쉽게 할 수 있는데 멀리 돌아간 것 같습니다. 서버를 열지 않고 파일 입출력이 가능합니다.

2019-04-03 09:12 UTC, GiPyoo requested changes
수고하셨습니다. 아래 리뷰 반영해 주시면 머지해드리겠습니다.

2019-04-03 09:12 UTC, GiPyoo commented on day4/fileReading.js
> +const array = function(){
함수 이름이 기능을 잘 설명하지 못하는 것 같습니다. 또, 함수의 이름은 동사여야합니다.

2019-04-03 12:45 UTC, GiPyoo approved these changes
수고하셨습니다. ⭐️

2019-04-03 12:45 UTC, GiPyoo commented on day4/server.js
> +
라인정리만 하면 될 것 같습니다.

2019-04-03 12:45 UTC, merged