[sem]Step1 calculator 코드리뷰 부탁드립니다🙏
JNU-econovation/javascript-study pull request #38
Opened 2019-03-31 11:47 UTC by jbj616

2019-03-31 12:07 UTC, mywnajsldkf reviewed
저는 잘 구현하셨다고 생각합니다! 잘 봤습니다

2019-03-31 12:07 UTC, mywnajsldkf commented on public/step-1/Cal.html
>    <script type="text/javascript" src="Calculator.js"></script>
각각 모듈로 분리한 이유를 여쭙고 싶습니다!

2019-03-31 13:51 UTC, GiPyoo requested changes
처음하시는데 수고하셨습니다. 기능적으로는 별 문제가 없지만, 하나의 함수가 여러가지 기능을 가지고 있는 경우도 존재하고, 클린 코드에서 지켜야할 네이밍이라던지, 코드 정리가 덜 된 느낌이었습니다. 아래 리뷰 반영 부탁드려요. :

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Button.js
> +function calculateBtn(){
버튼을 계산한다는 건가요?? 의미가 정확하지 않은 것 같습니다.

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Button.js
> +function clearBtn(){
버튼 보다는 input을 클리어 하는 것 같습니다.

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Button.js
> +   var cal = new Calculator();
축약어를 안쓰는 것이 클린 코드에 도움이 됩니다.

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Cal.html
> +  [output] : <strong id="result"></strong>
이것이 무엇인지 설명 부탁드려요

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Cal.html
> +    window.addEventListener('keydown', function(e) {
이부분도 자바스크립트 파일 내에서 함수화가 가능합니다. 혹시 잘 모르겠다면 질문답변 게시판 혹은 DM으로 언제든지 물어봐 주세요 . 😄

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Cal.html
> +        console.log("hihi");
이 로그는 제거 해도 될 것 같습니다.

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Calculator.js
> +function Calculator(){
이 함수를 구조적으로 더 줄일 수 있을 것 같습니다. 몇가지 기능 또한 같이 존재하는 것 같습니다. 따라서 기능별로 분리 해주세요.

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Check.js
> +
다른 함수사이에는 공백이 없습니다. 되도록이면 공백라인을 둘 때 자신만의 규칙 혹은 각 라인들의 연관성등을 고려하고 정리해주세요.

2019-03-31 13:51 UTC, GiPyoo commented on public/step-1/Util.js
> +
정리해주세요.

2019-03-31 13:56 UTC, forbid403 reviewed
잘 봤습니다 👍 속도가 정말 빠르시네요! 리뷰 반영 해 주세요 😄

2019-03-31 13:56 UTC, forbid403 commented on public/step-1/Calculator.js
> +  return num_1 + num_2;
camelCase 적용해서 네이밍 해주세요

2019-03-31 13:56 UTC, forbid403 commented on public/step-1/Calculator.js
> +  if(num_1/num_2 === NaN){
따로 변수로 받는 게 좋겠습니다

2019-03-31 13:56 UTC, forbid403 commented on public/step-1/Check.js
> +    alert('숫자 경고');
alert 상세 설명이 모호한 것 같습니다

2019-03-31 13:56 UTC, forbid403 commented on public/step-1/Check.js
> +    alert('연산자 경고!');
operator 이외의 입력을 아예 안 받거나 다른 방법을 쓰는게 좋을 것 같습니다

2019-03-31 13:56 UTC, forbid403 commented on public/step-1/Util.js
> +  document.getElementById("input").value = input;
반복되는 기능은 함수로 빼보세요

2019-03-31 13:56 UTC, forbid403 commented on public/step-1/Util.js
> +  input += " "+value+" ";
공백으로 나누는 것보다 다른 방식을 써보는게 어떨까요

2019-04-01 01:52 UTC, jbj616 commented on public/step-1/Cal.html
>    <script type="text/javascript" src="Calculator.js"></script>
기존에 한곳에 모든 코드를 작성하는 습관이 있어서 이번에 분리해 보았습니다.

2019-04-03 15:01 UTC, corykim0829 requested changes
좋은 코드 잘봤습니다~ 리뷰 반영 부탁해요~
아 그리고 커밋들이 모두 github 계정이랑 연동이 안된 것 같아요 그거 해결해주세요~

2019-04-03 15:01 UTC, corykim0829 commented on public/step-1/Button.js
> +   checkInput();
경고가 뜨면 계산이 진행되지 않도록 되어있나요?

2019-04-29 16:43 UTC, closed without merging