[hiro] step4 File I/O, Socket 구현 완료
JNU-econovation/javascript-study pull request #39
Opened 2019-04-02 15:27 UTC by hotheadfactory

nodejs, 콜백 너무 어렵습니다 @_@

2019-04-03 06:45 UTC, GiPyoo requested changes
파일읽는 부분은 잘하셨습니다. 👍 그런데 에코서버 부분에서 웹통신을하였는데, 이 것은 나중에 할 것이기 때문에 너무 과한 요구사항이었고, net을 활용하여 만드시고 push 해주세요. 고생하셨습니다. 😄

2019-04-03 06:45 UTC, GiPyoo commented on fileio_socket/fileio.js
> +    if(err) throw err;
console 로 알려 주는 것도 좋을 것 같습니다.

2019-04-03 06:45 UTC, GiPyoo commented on fileio_socket/fileio.js
> +var fs = require('fs');
재할당 재선언이 필요하지 않다면 var를 사용하는 것을 지양합시다.

2019-04-03 06:45 UTC, GiPyoo commented on fileio_socket/fileio.js
> +    for (i in array) {
i의 의미가 있게 써주시고 i 앞에 var 혹은 let 과 같은 선언자를 써주시기 바랍니다.

2019-04-03 06:45 UTC, GiPyoo commented on fileio_socket/public/socket.client.js
> +$(function(){
에코 서버인데 html을 이용한 http 서버통신은 요구사항을 잘 반영하지 못한 것 같습니다. net 모듈을 활용하여 주세요.

2019-04-03 06:45 UTC, GiPyoo commented on fileio_socket/socket.js
> +var express = require('express');
웹통신 아닙니다...

2019-04-03 13:25 UTC, hotheadfactory commented on fileio_socket/socket.js
> +var express = require('express');
수정했습니다ㅜㅜ

2019-04-04 02:16 UTC, GiPyoo requested changes
아직 리뷰가 반영 안된 부분이 있습니다. 확인해주시고 반영해주세요.

2019-04-05 02:26 UTC, corykim0829 approved these changes
수고하셨습니다.

2019-04-05 02:26 UTC, merged