[Cory] Step4 구현 완료
JNU-econovation/javascript-study pull request #41
Opened 2019-04-03 14:50 UTC by corykim0829

늦어서 죄송합니다. 어렵네요

2019-04-04 02:21 UTC, GiPyoo requested changes
고생하셨습니다. 아래 리뷰 반영 부탁합니다.

2019-04-04 02:21 UTC, GiPyoo commented on public/step4-node.js/echo_client.js
> +var net = require('net');
재선언 혹은 재할당을 막기 위해 let 혹은 const를 쓰는 것이 좋을 것 같습니다.

2019-04-04 02:21 UTC, GiPyoo commented on public/step4-node.js/read_by_lines.js
> +var reader = readline.createInterface(readStream, process.stdout);
이 부분 중에서도 모듈을 받는 부분의 경우는 var 보다 const가 나은 것 같습니다.

2019-04-05 02:17 UTC, Parkhyunseo commented on public/step4-node.js/echo_client.js
> +let net = require('net');
const 사용이 더 좋을 것 같네요

2019-04-05 02:17 UTC, Parkhyunseo commented on public/step4-node.js/echo_client.js
> +let client = net.connect({port:port, host: 'localhost'}, function() {
const 사용이 더 좋을 것 같네요

2019-04-05 02:17 UTC, Parkhyunseo commented on public/step4-node.js/echo_server.js
> +let net = require('net');
const 사용이 더 좋을 것 같네요

2019-04-05 02:17 UTC, Parkhyunseo commented on public/step4-node.js/echo_server.js
> +let server = net.createServer(function (client) {
const 사용이 더 좋을 것 같네요

2019-04-05 02:17 UTC, Parkhyunseo commented on public/step4-node.js/read_by_lines.js
> +let readline = require("readline");
const 사용이 더 좋을 것 같네요, module 선언은 맨위에 몰아서 하는게 좋습니다.

2019-04-05 02:17 UTC, Parkhyunseo commented on public/step4-node.js/read_by_lines.js
> +let readStream = fs.createReadStream('./output.txt', {flags: 'r'});
파일이름을 변수로 빼주세요

2019-04-29 00:09 UTC, GiPyoo approved these changes
수고하셨습니다.

2019-04-29 00:09 UTC, merged