[hiro] calculator-step1 구현 완료
JNU-econovation/javascript-study pull request #7
Opened 2019-02-18 11:16 UTC by hotheadfactory

수정후 다시 PR...

2019-02-18 15:21 UTC, corykim0829 commented
커밋 규칙에 맞게 커밋 로그 작성해주세요

2019-02-18 15:27 UTC, corykim0829 requested changes

2019-02-18 15:27 UTC, corykim0829 commented on calculator/calculator.js
> +    return a;
굳이 a 변수를 만들지 말고 if 문 안과 밖에서 각자 반환해도 될 것 같습니다

2019-02-18 15:27 UTC, corykim0829 commented on calculator/calculator.js
> +    var num = input.value.split(/[\*\/\+\-]/); // 연산자 기준으로 나눔
split으로 나눈 숫자들을 담고있는 배열이기 때문에 num보다는 더 포괄적인 변수명이 필요합니다. 예) splitedNumArray

2019-02-18 15:27 UTC, corykim0829 commented on calculator/calculator.js
> +    }
요구사항에서 각 연산은 각각의 함수로 구현되어야한다고 했습니다.

2019-02-18 15:28 UTC, corykim0829 commented
머지해드렸습니다~ 말씀드린 부분만 보완해서 step2 진행하시면 될 것 같습니다~

2019-02-18 15:28 UTC, merged

2019-02-21 17:36 UTC, hyukjin-lee commented
@corykim0829 @hotheadfactory  이 브랜치 마스터로 머지됐습니다.