feat : reset, add , calculate(ing)
JNU-econovation/javascript-study pull request #8
Opened 2019-02-19 08:00 UTC by mywnajsldkf

reset 부분과 버튼 add까지 구현했습니다.
현재 calculate에서 값을 result에 출력하는 곳에서 멈춤이 왔습니다.
우선은 올리고 좀 더 보안해보겠습니다.

2019-02-19 08:57 UTC, corykim0829 commented
공지사항 확인하고 PR 메세지 변경해주세요!

2019-02-19 09:09 UTC, corykim0829 requested changes
열심히 노력한 흔적이 보입니다. 수고하셨습니다! 과제 요구사항에서 예외나 오류 처리를 할 수 없는 부분을 추가로 구현 후에 푸쉬해주세요! 네이밍 컨벤션 지속적으로 보면서 코드 작성하시면 좋습니다~

2019-02-19 09:09 UTC, corykim0829 commented on public/calculator-step1/JScalculator.html
> +    <script src="cal_calculate.js"></script>
각각 모듈로 분리한 이유가 궁금하네요. 계산기 기능이니 굳이 분리하지 않고 하나의 js에서 작성해도 될 것 같습니다!

2019-02-19 09:09 UTC, corykim0829 commented on public/calculator-step1/JScalculator.html
> +    </style>
다음 단계 진행시에는 css파일로 분리하는 작업을 해보세요 생각보다 어렵지 않습니다~

2019-02-19 09:09 UTC, corykim0829 commented on public/calculator-step1/cal_calculate.js
> +    var number = input.split(/[\*\/\+\-]/);
여러 숫자들을 담으니 number 보다는 numbers나 배열임을 고려해 numbers로 하는게 좋습니다.

2019-02-19 09:09 UTC, corykim0829 commented on public/calculator-step1/cal_calculate.js
> +    var left_number = number[0];
변수 네이밍은 camel case를 원칙으로 진행 중입니다~ leftNumber로 바꿔주세요(이하 변수명들도 동일)

2019-02-19 09:09 UTC, corykim0829 commented on public/calculator-step1/cal_calculate.js
> +        function plus(after_leftnum,after_rightnum){
함수를 안에 선언해버리면 다른 곳에서 사용할 수 없습니다! 밖에서 선언해주세요

2019-02-19 09:09 UTC, corykim0829 commented on public/calculator-step1/cal_calculate.js
> +
if문보다 switch문을 쓴다면 더 깔끔할 것 같습니다. switch문으로 함수를 호출하세요

2019-02-19 09:09 UTC, corykim0829 commented on public/calculator-step1/cal_calculate.js
> +function start_cal(){
함수안에 너무 많은게 있습니다. 조금 더 분리해보세요!

2019-02-21 17:34 UTC, hyukjin-lee commented on public/calculator-step1/JScalculator.html
> +    <script src="cal_calculate.js"></script>
이건 마치 함수를 전부 하나의 클래스 파일로 쪼개는 것과 같은 모습입니다. 계산기라는 하나의 개념이 하는 일들은 계산기를 담당하는 파일 하나에 구현하는 것이 유지보수에 더 좋아보입니다. 이렇게 각 함수를 다 파일로 쪼개버리면 추후에 같은 값을 공유하면서 로직을 개발해야될 때 더 복잡해질 수 있어요

2019-02-24 04:11 UTC, GiPyoo reviewed
잘하고 있습니다. 아래 리뷰 반영해주세요.

2019-02-24 04:11 UTC, GiPyoo commented on public/calculator-step1/CalculatorSource.js
> +}
이 함수는 계산을 시작하는 함수라기보다는 텍스트를 나누는 함수인 것 같습니다. 함수이름 수정이 필요해 보입니다.

2019-02-24 04:11 UTC, GiPyoo commented on public/calculator-step1/CalculatorSource.js
> +
반복적인 parseInt를 줄일 수 있을 것 같습니다.

2019-02-24 04:11 UTC, GiPyoo commented on public/calculator-step1/CalculatorSource.js
> +    }
return을 사용한다면 break 는 필요 없어보입니다.

2019-02-24 04:11 UTC, GiPyoo commented on public/calculator-step1/CalculatorSource.js
> +}
var input을 선언하지 않고 한 줄로 만들 수 있을 것 같습니다
그리고 함수명이 give는 어울리지 않는 것 같습니다. 입력한 것을 보여주는 함수입니다. 생각해보세용

2019-02-24 04:11 UTC, GiPyoo commented on public/calculator-step1/CalculatorSource.js
> +    }
그리고 이함수는 사용 되고 있지 않습니다.

2019-02-24 05:45 UTC, corykim0829 commented on public/calculator-step1/CalculatorSource.js
> +    var numbers = input.split(/[\*\/\+\-]/);
input.value를 split하지 않아도 정상적으로 실행 되나요?

2019-02-24 05:45 UTC, corykim0829 commented on public/calculator-step1/CalculatorSource.js
> +    switch(Symbol){
symbol 대소문자 오류입니다.

2019-03-02 04:19 UTC, mywnajsldkf commented on public/calculator-step1/CalculatorSource.js
> +
전역변수를 사용하라는 말씀이신가요? 아니면 연산하는 함수들을 하나로 묶으라는 말씀이신가요? 아니면 다른 건가요?

2019-03-02 04:37 UTC, GiPyoo commented
계산에 들어가기전에 파스인트를 하고 넘겨주면 파스인트를 많이 줄일수 있을겁니다 😀

2019-03-03 03:02 UTC, mywnajsldkf reviewed
함수 작성하는 중에 어려움이 와서 생활코딩을 다시 듣고 있습니다.
그래서 제출기한을 지키지 못했습니다.
죄송합니다. 앞으로는 잘 지키도록 노력하겠습니다!

2019-03-04 01:32 UTC, GiPyoo reviewed
예외처리만 하면 끝날 것 같내요 아래 리뷰 반영해주세요.

2019-03-04 01:32 UTC, GiPyoo commented on public/calculator-step1/JScalculator.html
> +                <input type="text" id="result" style="text-align:right;" readonly="readonly">
input {
    text-align : right ;
}
이걸 css 에 추가 해주세요.

2019-03-04 01:32 UTC, GiPyoo commented on public/calculator-step1/CalculatorSource.js
> +
공백라인 정리해주세요

2019-03-05 15:02 UTC, corykim0829 requested changes
전체적으로 정말 깔끔하게 잘 구현하셨습니다! 예외 처리 기능을 추가하시고 연산을  switch 문이 아닌 객체와 함수를 사용해 구현해보세요 코드가 훨씬 줄어들 겁니다! 다른 분들 구현하신 것도 참고해보면서 피드백 반영하시고 push해주세요!

2019-03-05 15:02 UTC, corykim0829 commented on public/calculator-step1/CalculatorSource.js
> +function categorize(input){
주로 분류 과정에서 예외 처리를 해주시면 될 것 같습니다.

2019-03-06 14:34 UTC, forbid403 commented on public/calculator-step1/CalculatorSource.js
> +
공백쓰 제거쓰해주세용

2019-03-10 15:37 UTC, corykim0829 approved these changes
잘하셨습니다! 예외 처리 부분이나 함수명, parseFloat의 사용이 조금 아쉬운 부분이 있지만 충분히 step2를 진행하면서 수정할 수 있을 것 같아 일단 머지해 드리겠습니다. closed PR에 가셔서 다른 멤버들은 어떻게 step1을 구현했는지 봐보시고 제가 오프라인으로 리뷰 몇개 더 해드리겠습니다. 노트북도 고장났는데 수고 많으셨습니다. Judy님!

2019-03-10 15:37 UTC, corykim0829 commented on public/calculator-step1/CalculatorSource.js
> +
불필요한 공백은 항상 마지막에 체크해주세요!

2019-03-10 15:37 UTC, corykim0829 commented on public/calculator-step1/CalculatorSource.js
> +function checkLength(numbers) {
길이를 체크하기는 하지만 실질적인 예외는 길이 때문에 발생하는 것이 아니기 때문에 함수명을 수정해야할 것 같습니다!

2019-03-10 15:37 UTC, corykim0829 commented on public/calculator-step1/CalculatorSource.js
> +    return parseInt(leftNumber)+parseInt(rightNumber);
plus에만 paresInt를 하는게 올바른 계산식이 나오기는 하지만 원래는 모든 함수에서 해줘야합니다. 그리고 parseFloat으로 해야 소수자리 까지 계산이 가능합니다. 모든 함수에 parseFloat을 추가하지 않고 해결하는 방법을 생각해보세요

2019-03-10 15:37 UTC, corykim0829 commented on public/calculator-step1/CalculatorSource.js
> +    switch(symbol){
step2를 진행할 때 스위치문을 사용하지 않고 처리하는 법을 생각해보세요~

2019-03-10 15:37 UTC, corykim0829 commented on public/calculator-step1/CalculatorSource.js
> +function reset() {
reset 보다는 clearOOO 가 맞는 함수명일 것 같네요!

2019-03-10 15:37 UTC, merged